apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: enterprise-monorepo
  description: A production-ready monorepo architecture for enterprise applications
  annotations:
    github.com/project-slug: ${{values.github_org}}/${{values.github_repo}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - typescript
    - javascript
    - monorepo
    - nextjs
    - nestjs
    - turborepo
spec:
  type: template
  lifecycle: experimental
  owner: ${{values.owner}}
  system: ${{values.system | default('enterprise-platform')}}
