site_name: "Enterprise Monorepo Architecture"
site_description: "Documentation for the Enterprise Monorepo Template"

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
  - Architecture:
      - Overview: architecture/overview.md
      - Frontend: architecture/frontend.md
      - Backend: architecture/backend.md
      - Shared Packages: architecture/shared-packages.md
  - Development:
      - Workflow: development/workflow.md
      - Testing: development/testing.md
      - CI/CD: development/ci-cd.md
  - Infrastructure:
      - Docker: infrastructure/docker.md
      - Kubernetes: infrastructure/kubernetes.md
      - Terraform: infrastructure/terraform.md
  - Backstage:
      - Template Integration: backstage-integration.md
      - Working with TechDocs: techdocs-guide.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
